src/Entity/Packages/Architecture.php
<?php

namespace App\Entity\Packages;

// @TODO as embeddable entity?
class Architecture
{
    public const X86_64 = 'x86_64';
    public const I686 = 'i686';
    public const ANY = 'any';
}

src/Entity/Packages/Files.php
<?php

namespace App\Entity\Packages;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilesRepository")
 */
class Files implements \IteratorAggregate, \JsonSerializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $files;

    /**
     * @var Package
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Packages\Package", mappedBy="files", fetch="LAZY")
     */
    private $package;

    /**
     * @param string $files
     */
    private function __construct(string $files)
    {
        $this->files = $files;
    }

    /**
     * @param string[] $filesArray
     * @return Files
     */
    public static function createFromArray(array $filesArray): self
    {
        sort($filesArray);
        return new self(implode("\n", $filesArray));
    }

    /**
     * @return Package
     */
    public function getPackage(): Package
    {
        return $this->package;
    }

    /**
     * @param Package $package
     * @return Files
     */
    public function setPackage(Package $package): Files
    {
        $this->package = $package;
        return $this;
    }

    /**
     * @return \Iterator
     */
    public function getIterator(): \Iterator
    {
        return new \ArrayIterator($this->getFiles());
    }

    /**
     * @return string[]
     */
    private function getFiles(): array
    {
        if (empty($this->files)) {
            return [];
        } else {
            return explode("\n", $this->files);
        }
    }

    /**
     * @return array
     */
    public function jsonSerialize(): array
    {
        return $this->getFiles();
    }
}

src/Entity/Packages/Package.php
<?php

namespace App\Entity\Packages;

use App\Entity\Packages\Relations\CheckDependency;
use App\Entity\Packages\Relations\Conflict;
use App\Entity\Packages\Relations\Dependency;
use App\Entity\Packages\Relations\MakeDependency;
use App\Entity\Packages\Relations\OptionalDependency;
use App\Entity\Packages\Relations\Provision;
use App\Entity\Packages\Relations\Replacement;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PackageRepository")
 * @ORM\Table(indexes={
 *     @ORM\Index(columns={"buildDate"}),
 *     @ORM\Index(columns={"name"})
 * })
 */
class Package implements \JsonSerializable
{
    private const PKGEXT = '.pkg.tar.xz';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Repository
     *
     * @ORM\ManyToOne(targetEntity="Repository", inversedBy="packages")
     */
    private $repository;

    /**
     * @var string
     *
     * @ORM\Column(name="fileName", type="string")
     */
    private $fileName;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="base", type="string")
     */
    private $base;

    /**
     * @var string
     *
     * @ORM\Column(name="version", type="string")
     */
    private $version;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string")
     */
    private $description = '';

    /**
     * @var string[]
     *
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $groups = [];

    /**
     * @var integer
     *
     * @ORM\Column(name="compressedSize", type="bigint")
     */
    private $compressedSize = 0;

    /**
     * @var integer
     *
     * @ORM\Column(name="installedSize", type="bigint")
     */
    private $installedSize = 0;

    /**
     * @var string
     *
     * @ORM\Column(name="md5sum", type="string", length=32, nullable=true)
     */
    private $md5sum;

    /**
     * @var string
     *
     * @ORM\Column(name="sha256sum", type="string", length=64, nullable=true)
     */
    private $sha256sum;

    /**
     * @var string
     *
     * @ORM\Column(name="pgp_signature", type="blob", nullable=true)
     */
    private $pgpSignature;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", nullable=true)
     */
    private $url;

    /**
     * @var string[]
     *
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $licenses;

    /**
     * @var string
     *
     * @ORM\Column(name="architecture", type="string")
     */
    private $architecture;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="buildDate", type="datetime", nullable=true)
     */
    private $buildDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="mTime", type="datetime", nullable=true)
     */
    private $mTime;

    /**
     * @var Packager
     *
     * @ORM\Embedded(class="App\Entity\Packages\Packager")
     */
    private $packager;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\Replacement",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $replaces;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\Conflict",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $conflicts;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\Provision",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $provides;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\Dependency",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $depends;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\OptionalDependency",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $optdepends;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\MakeDependency",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $makedepends;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Packages\Relations\CheckDependency",
     *     mappedBy="source",
     *     cascade={"persist"},
     *     orphanRemoval=true
     * )
     */
    private $checkdepends;

    /**
     * @var Files
     *
     * @ORM\OneToOne(
     *     targetEntity="App\Entity\Packages\Files",
     *     cascade={"remove", "persist"},
     *     fetch="LAZY",
     *     inversedBy="package"
     * )
     */
    private $files;

    /**
     * @param Repository $repository
     * @param string $name
     * @param string $version
     * @param string $architecture
     */
    public function __construct(Repository $repository, string $name, string $version, string $architecture)
    {
        $this->name = $name;
        $this->base = $name;
        $this->repository = $repository;
        $this->version = $version;
        $this->architecture = $architecture;

        $this->base = $name;
        $this->fileName = $name . '-' . $version . '-' . $architecture . self::PKGEXT;

        $this->makedepends = new ArrayCollection();
        $this->checkdepends = new ArrayCollection();
        $this->optdepends = new ArrayCollection();
        $this->conflicts = new ArrayCollection();
        $this->depends = new ArrayCollection();
        $this->provides = new ArrayCollection();
        $this->replaces = new ArrayCollection();
    }

    /**
     * @param Repository $repository
     * @param \App\ArchLinux\Package $databasePackage
     * @return Package
     */
    public static function createFromPackageDatabase(
        Repository $repository,
        \App\ArchLinux\Package $databasePackage
    ): Package {
        $package = new self(
            $repository,
            $databasePackage->getName(),
            $databasePackage->getVersion(),
            $databasePackage->getArchitecture()
        );

        return $package->updateFromPackageDatabase($databasePackage);
    }

    /**
     * @param \App\ArchLinux\Package $databasePackage
     * @return Package
     */
    public function updateFromPackageDatabase(\App\ArchLinux\Package $databasePackage): Package
    {
        $this->setName($databasePackage->getName());
        $this->setVersion($databasePackage->getVersion());
        $this->setArchitecture($databasePackage->getArchitecture());

        $this->setFileName($databasePackage->getFileName());
        $this->setUrl($databasePackage->getUrl());
        $this->setDescription($databasePackage->getDescription());
        $this->setBase($databasePackage->getBase());
        $this->setBuildDate($databasePackage->getBuildDate());
        $this->setCompressedSize($databasePackage->getCompressedSize());
        $this->setInstalledSize($databasePackage->getInstalledSize());
        $this->setMd5sum($databasePackage->getMd5sum());
        $this->setPackager(Packager::createFromString($databasePackage->getPackager()));
        $this->setSha256sum($databasePackage->getSha256sum());
        $this->setPgpSignature($databasePackage->getPgpSignature());
        $this->setMTime($databasePackage->getMTime());
        $this->setLicenses($databasePackage->getLicenses());
        $this->setGroups($databasePackage->getGroups());

        $this->getDependencies()->clear();
        foreach ($databasePackage->getDepends() as $depend) {
            $this->addDependency(Dependency::createFromString($depend));
        }

        $this->getConflicts()->clear();
        foreach ($databasePackage->getConflicts() as $conflict) {
            $this->addConflict(Conflict::createFromString($conflict));
        }

        $this->getReplacements()->clear();
        foreach ($databasePackage->getReplaces() as $replacement) {
            $this->addReplacement(Replacement::createFromString($replacement));
        }

        $this->getOptionalDependencies()->clear();
        foreach ($databasePackage->getOptDepends() as $optDepend) {
            $this->addOptionalDependency(OptionalDependency::createFromString($optDepend));
        }

        $this->getProvisions()->clear();
        foreach ($databasePackage->getProvides() as $provide) {
            $this->addProvision(Provision::createFromString($provide));
        }

        $this->getMakeDependencies()->clear();
        foreach ($databasePackage->getMakeDepends() as $makeDepend) {
            $this->addMakeDependency(MakeDependency::createFromString($makeDepend));
        }

        $this->getCheckDependencies()->clear();
        foreach ($databasePackage->getCheckDepends() as $checkDepend) {
            $this->addCheckDependency(CheckDependency::createFromString($checkDepend));
        }

        $this->setFiles(Files::createFromArray($databasePackage->getFiles()));

        return $this;
    }

    /**
     * @return Collection
     */
    public function getDependencies(): Collection
    {
        return $this->depends;
    }

    /**
     * @param Dependency $dependency
     * @return Package
     */
    public function addDependency(Dependency $dependency)
    {
        $dependency->setSource($this);
        $this->depends->add($dependency);
        return $this;
    }

src/Entity/Packages/Packager.php
<?php

namespace App\Entity\Packages;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Embeddable
 */
class Packager implements \JsonSerializable
{
    /**
     * @var string
     *
     * @ORM\Column(nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(nullable=true)
     */
    private $email;

    /**
     * @param string $name
     * @param string $email
     */
    public function __construct(string $name, string $email)
    {
        $this->name = $name;
        $this->email = $email;
    }

    /**
     * @param string $packagerDefinition
     * @return Packager
     */
    public static function createFromString(string $packagerDefinition): self
    {
        preg_match('/([^<>]+)(?:<(.+?)>)?/', $packagerDefinition, $matches);
        $name = trim(!empty($matches[1]) ? $matches[1] : $packagerDefinition);
        $email = trim(isset($matches[2]) ? $matches[2] : '');

        return new self($name, $email);
    }

    /**
     * @return array
     */
    public function jsonSerialize(): array
    {
        return [
            'name' => $this->getName(),
            'email' => $this->getEmail()
        ];
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }
}

src/Entity/Packages/Relations/AbstractRelation.php
<?php

namespace App\Entity\Packages\Relations;

use App\Entity\Packages\Package;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AbstractRelationRepository")
 * @ORM\InheritanceType(value="SINGLE_TABLE")
 * @ORM\Table(name="packages_relation", indexes={@ORM\Index(columns={"target_name"})})
 */
abstract class AbstractRelation
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $targetName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $targetVersion;

    /**
     * @var Package
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Packages\Package")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $target;

    /**
     * @var Package
     */
    protected $source;

    /**
     * @param null|string $targetName
     * @param null|string $targetVersion
     */
    public function __construct(?string $targetName, ?string $targetVersion = null)
    {
        $this->targetName = $targetName;
        $this->targetVersion = $targetVersion;
    }

    /**
     * @param string $targetDefinition
     * @return static
     */
    public static function createFromString(string $targetDefinition): self
    {
        if (preg_match('/^([\w-]+?)((?:<|<=|=|>=|>)+[\w\.:]+)/', $targetDefinition, $matches) > 0) {
            $targetName = $matches[1];
            $targetVersion = $matches[2];
        } elseif (preg_match('/^([\w-]+)/', $targetDefinition, $matches) > 0) {
            $targetName = $matches[1];
            $targetVersion = null;
        } else {
            $targetName = $targetDefinition;
            $targetVersion = null;
        }
        return new static($targetName, $targetVersion);
    }

    /**
     * @param Package $package
     * @return $this
     */
    public function setSource(Package $package)
    {
        $this->source = $package;
        return $this;
    }

    /**
     * @return Package
     */
    public function getSource(): Package
    {
        return $this->source;
    }

    /**
     * @return Package
     */
    public function getTarget(): ?Package
    {
        return $this->target;
    }

    /**
     * @param Package|null $target
     */
    public function setTarget(?Package $target)
    {
        $this->target = $target;
    }

    /**
     * @return string
     */
    public function getTargetName(): string
    {
        return $this->targetName;
    }

    /**
     * @return string
     */
    public function getTargetVersion(): ?string
    {
        return $this->targetVersion;
    }
}

src/Entity/Packages/Relations/CheckDependency.php
<?php

namespace App\Entity\Packages\Relations;

use App\Entity\Packages\Package;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class CheckDependency extends AbstractRelation
{
    /**
     * @var Package
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Packages\Package", inversedBy="checkdepends")
     */
    protected $source;
}

src/Entity/Packages/Relations/Conflict.php
<?php

namespace App\Entity\Packages\Relations;

use App\Entity\Packages\Package;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Conflict extends AbstractRelation
{
    /**
     * @var Package
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Packages\Package", inversedBy="conflicts")
     */
    protected $source;
}

src/Entity/Packages/Relations/Dependency.php
<?php

namespace App\Entity\Packages\Relations;

use App\Entity\Packages\Package;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Dependency extends AbstractRelation
{
    /**
     * @var Package
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Packages\Package", inversedBy="depends")
     */
    protected $source;
}

src/Entity/Packages/Relations/MakeDependency.php
<?php

namespace App\Entity\Packages\Relations;

use App\Entity\Packages\Package;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class MakeDependency extends AbstractRelation
{
    /**
     * @var Package
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Packages\Package", inversedBy="makedepends")
     */
    protected $source;
}

templates/package/index.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('build/js/package.js') }}"></script>
{% endblock %}

{% block title %}{{ package.name }}{% endblock %}

{% block robots %}{% if package.repository.testing == true %}no{% endif %}index,follow{% endblock %}

{% block body %}
    <h1 class="mb-4">{{ package.name }}</h1>
    <div class="row mw-100">
        <div class="col-12 col-xl-6">
            <h2 class="mb-3">Paket-Details</h2>
            <table class="table table-sm">
                <colgroup>
                    <col class="w-20">
                </colgroup>
                <tr>
                    <th>Name</th>
                    <td>{{ package.name }}</td>
                </tr>
                <tr>
                    <th>Version</th>
                    <td>{{ package.version }}</td>
                </tr>
                <tr>
                    <th>Beschreibung</th>
                    <td>{{ package.description }}</td>
                </tr>
                {% if package.url %}
                    <tr>
                        <th>URL</th>
                        <td class="mw-50vw">
                            {% if package.url matches('#^(https?|ftp)://.+$#') %}
                                <a class="break-word" rel="nofollow" href="{{ package.url }}">{{ package.url }}</a>
                            {% else %}
                                {{ package.url }}
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <th>Lizenzen</th>
                    <td>{{ package.licenses | join(', ') }}</td>
                </tr>
                <tr>
                    <th>Repositorium</th>
                    <td>
                        <a href="{{ path('app_packages_index', {'repository': package.repository.name}) }}">{{ package.repository.name }}</a>
                    </td>
                </tr>
                <tr>
                    <th>Architektur</th>
                    <td>
                        {{ package.architecture }}
                    </td>
                </tr>
                <tr>
                    <th>Gruppen</th>
                    <td>{{ package.groups | join(', ') }}</td>
                </tr>
                {% if package.packager %}
                    <tr>
                        <th>Packer</th>
                        <td>
                            {% if package.packager.email %}
                                <a rel="nofollow"
                                   href="mailto:{{ package.packager.email }}">{{ package.packager.name }}</a>
                            {% else %}
                                {{ package.packager.name }}
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <th>Erstellt am</th>
                    <td>{{ package.builddate | date }}</td>
                </tr>
                <tr>
                    <th>Veröffentlicht am</th>
                    <td>{{ package.mTime | date }}</td>
                </tr>
                <tr>
                    <th>Quelltext</th>
                    <td><a href="{{ cgit_url }}tree/trunk?h=packages/{{ package.base }}">Quelldateien</a>,
                        <a href="{{ cgit_url }}log/trunk?h=packages/{{ package.base }}">Änderungshistorie</a></td>
                </tr>
                <tr>
                    <th>Bugs</th>
                    <td><a href="https://bugs.archlinux.org/index.php?string=%5B{{ package.name }}%5D">Bug-Tracker</a>
                    </td>
                </tr>
                <tr>
                    <th>Paket</th>
                    <td>
                        <a href="{{ path(
                            'app_mirror_package',
                            {'repository': package.repository.name, 'architecture': package.repository.architecture, 'file': package.filename}
                        ) }}">{{ package.filename }}</a>
                    </td>
                </tr>
                <tr>
                    <th>PGP-Signatur</th>
                    <td>
                        <a href="{{ path(
                            'app_mirror_package',
                            {'repository': package.repository.name, 'architecture': package.repository.architecture, 'file': package.filename~'.sig'}
                        ) }}">{{ package.filename }}
                            .sig</a></td>
                </tr>
                <tr>
                    <th>Paket-Größe</th>
                    <td>{{ package.compressedSize | format_bytes }}</td>
                </tr>
                <tr>
                    <th>Installations-Größe</th>
                    <td>{{ package.installedSize | format_bytes }}</td>
                </tr>
            </table>
        </div>
        <div class="col-12 col-xl-6">
            <h2 class="mb-3 mt-5 mt-xl-0">Abhängigkeiten</h2>

            {% macro relate(name, relations) %}
                {% if relations | length > 0 %}
                    {% set listLimit = 10 %}
                    {% set listClass %}list-target-{{ random() }}{% endset %}
                    <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                        <h3>{{ name }}</h3>
                        <ul class="list-unstyled pl-4">
                            {# @var relation \App\Entity\Packages\Relations\AbstractRelation #}
                            {% for relation in relations %}

                                {% if loop.index == listLimit and loop.length > listLimit %}
                                    <li class="mt-1 show {{ listClass }}">
                                        <a href="#" class="text-secondary" data-target=".{{ listClass }}" data-toggle="collapse" >
                                            mehr&hellip;
                                        </a>
                                    </li>
                                {% endif %}
                                <li{% if loop.index >= listLimit and loop.length > listLimit %} class="collapse {{ listClass }}"{% endif %}>
                                    {% if relation.target %}
                                        <a href="{{ path(
                                        'app_packagedetails_index',
                                        {'repo': relation.target.repository.name, 'arch': relation.target.repository.architecture, 'pkgname': relation.target.name}
                                    ) }}">{{ relation.targetName }}</a>{{ relation.targetVersion }}
                                    {% else %}
                                        {{ relation.targetName }}{{ relation.targetVersion }}
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endmacro %}
            {% macro related(name, packages) %}
                {% if packages | length > 0 %}
                    {% set listLimit = 10 %}
                    {% set listClass %}list-target-{{ random() }}{% endset %}
                    <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                        <h3>{{ name }}</h3>
                        <ul class="list-unstyled pl-4">
                            {# @var package \App\Entity\Packages\Package #}
                            {% for package in packages %}

                                {% if loop.index == listLimit and loop.length > listLimit %}
                                    <li class="mt-1 show {{ listClass }}">
                                        <a href="#" class="text-secondary" data-target=".{{ listClass }}" data-toggle="collapse" >
                                            mehr&hellip;
                                        </a>
                                    </li>
                                {% endif %}
                                <li{% if loop.index >= listLimit and loop.length > listLimit %} class="collapse {{ listClass }}"{% endif %}>
                                    <a href="{{ path(
                                        'app_packagedetails_index',
                                        {'repo': package.repository.name, 'arch': package.repository.architecture, 'pkgname': package.name}
                                    ) }}">{{ package.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endmacro %}
            {% import _self as macro %}

            <div class="row mw-100">
                {{ macro.relate('von', package.dependencies) }}
                {{ macro.relate('optional von', package.optionalDependencies) }}

                {{ macro.relate('stellt bereit', package.provisions) }}
                {{ macro.relate('ersetzt', package.replacements) }}
                {{ macro.relate('kollidiert mit', package.conflicts) }}

                {{ macro.relate('Bauen von', package.makeDependencies) }}
                {{ macro.relate('Test von', package.checkDependencies) }}

                {{ macro.related('benötigt von', inverse_depends) }}
                {{ macro.related('optional für', inverse_optdepends) }}
                {{ macro.related('Zum Bauen von', inverse_makedepends) }}
            </div>
        </div>

        <div class="col-12">
            <h2 class="mb-3 mt-5 mt-xl-0">Dateien</h2>

            <button id="fileListToggle" class="btn btn-outline-secondary btn-sm ml-4" type="button"
                    data-toggle="collapse"
                    data-target="#fileList" aria-expanded="false" aria-controls="fileList">Dateien anzeigen
            </button>
            <ul id="fileList" class="d-none collapse list-unstyled pl-4" data-ajax="{{ path(
                'app_packagedetails_files',
                {'repo': package.repository.name, 'arch': package.repository.architecture, 'pkgname': package.name}
            ) }}">
            </ul>

        </div>
    </div>
{% endblock %}